package ar.edu.unlam.pb2.CallCenter;

public enum Provincia {
	BUENOSAIRES, CATAMARCA, CHACO, CHUBUT, CORDOBA, CORRIENTES, ENTRERIOS, FORMOSA, JUJUY, LAPAMPA, LARIOJA, MENDOZA,
	MISIONES, NEUQUEN, RIONEGRO, SALTA, SANJUAN, SANLUIS, SANTACRUZ, SANTAFE, SANTIAGODELESTERO, TIERRADELFUEGO,
	TUCUMAN;
}
